### ISSUE TITLE
Contao 4.9-RC1: Fehlfunktion in "Startpunkt einer Website"

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-trueurl#10]
Normalerweise werden bei einem "Startpunkt einer Website" die Optionen

- Vererbung des Startpunkt-Alias
- Standardmäßig die Alias-Vererbung aktivieren

angezeigt. Dies ist auch der Fall, wenn ich einen neuen Startpunkt anlege. Sobald ich jedoch die Option "Sprachen-Fallback" aktiviere, werden die beiden Optionen durch die Optionen einer normalen Seite ersetzt:

- Alias von Elternseite erben
- Alias des Startpunkts ignorieren
- Von Alias-Vererbung ausschließen

**Comment by dmolineus** [comment]
Verhalten geändert durch https://github.com/contao/contao/pull/717, behoben durch 12f2923acba2bfc88f49d377205c8bf5a2cb0d48
