### ISSUE TITLE
Seite nicht gefunden bei Contao 3.5

### ISSUE THREAD

**Issue by basistom** [hofff/contao-trueurl#5]
Die Version 2.0.1 (freigegeben bis Contao < 4) führt dazu, dass bei dem Aufruf von Unterseiten im FE (alles außer '/') nur "Seite nicht gefunden" zurückgegeben wird.

Die Option "URLs umschreiben" oder die .htaccess konnten dabei das Auftreten nicht lösen.

Im Systemlog kommt lediglich die Meldung "No active page for page ID "5", host "…" and languages "de-DE, de, en, en-US" (http://…)

**Comment by frontendschlampe** [comment]
should be fixed in v2.2.0 and we changed name/repo to https://github.com/hofff/contao-trueurl - we will update all information the next days

If there will be some more problems, please let us know. ;-)
