### ISSUE TITLE
Function name must be a string (labelPage method)

### ISSUE THREAD

**Issue by siemendev** [hofff/contao-trueurl#6]
Hi!
Ich falle derzeit beim ausprobieren von PHP7 mit Contao bei dieser Extension auf die Nase - folgender Fehler wird geworfen:

> Fatal error: Uncaught exception Error with message Function name must be a string thrown in system/modules/backboneit_trueurl/TrueURLBackend.php on line 79
> # 0 system/modules/core/drivers/DC_Table.php(3763): TrueURLBackend->labelPage(Array, 'GOA.ONE', Object(Contao\DC_Table), '', false, false)
> # 1 system/modules/core/drivers/DC_Table.php(3425): Contao\DC_Table->generateTree('tl_page', '1', Array, true, -20, false, false, false, false)
> # 2 system/modules/core/drivers/DC_Table.php(367): Contao\DC_Table->treeView()
> # 3 system/modules/core/classes/Backend.php(650): Contao\DC_Table->showAll()
> # 4 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('article')
> # 5 contao/main.php(20): Contao\BackendMain->run()
> # 6 {main}

wenn ich allerdings folgende Stelle in TrueURLBackend.php (siehe Zeile 79) ändere von 

``` php
(73)public function labelPage($row, $label, DataContainer $dc=null, $imageAttribute='', $blnReturnImage=false, $blnProtected=false) {
(74)        $blnWasRecurse = self::$blnRecurse;
(75)        $arrCallback = $blnWasRecurse ? array('tl_page', 'addIcon') : $GLOBALS['TL_DCA']['tl_page']['list']['label']['bbit_turl'];
(76)
(77)        self::$blnRecurse = true;
(78)        $this->import($arrCallback[0]);
(79)        $label = $this->$arrCallback[0]->$arrCallback[1]($row, $label, $dc, $imageAttribute, $blnReturnImage, $blnProtected);
(80)        self::$blnRecurse = false;


        (...)
}
```

zu

``` php
(73)public function labelPage($row, $label, DataContainer $dc=null, $imageAttribute='', $blnReturnImage=false, $blnProtected=false) {
(74)        $blnWasRecurse = self::$blnRecurse;
(75)        $arrCallback = $blnWasRecurse ? array('tl_page', 'addIcon') : $GLOBALS['TL_DCA']['tl_page']['list']['label']['bbit_turl'];
(76)
(77)        self::$blnRecurse = true;
(78)        $this->import('tl_page');
(79)        $label = $this->tl_page->addIcon($row, $label, $dc, $imageAttribute, $blnReturnImage, $blnProtected);
(80)        self::$blnRecurse = false;


        (...)
}
```

dann läuft alles einwandfrei... woran kann das liegen?

**Comment by backbone87** [comment]
wahrscheinlich daran das: `$this->$arrCallback[0]->$arrCallback[1]` als dynamische syntax zum methoden aufruf nicht mehr unstützt wird.
`$this->{$arrCallback[0]}->{$arrCallback[1]}` sollte funktionieren
besser wäre
`call_user_func_array(array($this->{$arrCallback[0]}, $arrCallback[1]), func_get_args())`

**Comment by siemendev** [comment]
Zu der Lösung bin ich auch gerade gekommen - wird das in eine zukünftige Extension-Version integriert?

Danke!

**Comment by backbone87** [comment]
ich werde das korrigieren
