### ISSUE TITLE
Seiten vom Typ "Ordner" werden nicht ausgelassen

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-trueurl#7]
Seiten vom Typ "Ordner" von der Erweiterung terminal42/contao-folderpage werden bei der Vererbung nicht ausgelassen und haben teilweise die Einstellungen von trueurl sichtbar

Regulärer Ausdruck (PREG) für Anfragepfad
Referenzen im Ausdruck auf GET Parameter abbilden
Mit "Seite nicht gefunden" Antworten bei nicht Übereinstimmung

Aber nur die einzelnen Einstellungen, nicht die Palettenüberschrift ist sichtbar

**Comment by frontendschlampe** [comment]
Seitenalias des Ordners wird mitvererbt

**Comment by dmolineus** [comment]
Wir aktivieren nun in der Erweiterung die Alias-Einstellungen für die Folderpage, sodass man diese mitnutzen kann.
